# Project-wide Gradle settings.

# JVM arguments
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Enable AAPT2 PNG crunching
android.enablePngCrunchInReleaseBuilds=true

# Architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# New architecture (TurboModules/Fabric)
newArchEnabled=true

# Hermes JS engine
hermesEnabled=true

# Expo image formats
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false

# Enable network inspector
EX_DEV_CLIENT_NETWORK_INSPECTOR=true

# Legacy packaging
expo.useLegacyPackaging=false

# Kotlin version alignée avec Expo SDK 53 by Simon NDENDAH
kotlin.version=1.9.22