# Paramètres JVM
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Crunch PNG en release
android.enablePngCrunchInReleaseBuilds=true

# Architectures supportées
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Nouvelle architecture RN
newArchEnabled=false

# Moteur JS
hermesEnabled=true

# Support images
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false

# Inspecteur réseau
EX_DEV_CLIENT_NETWORK_INSPECTOR=true

# Packaging natif
expo.useLegacyPackaging=false

# ✅ Versions Kotlin / Compose Compiler
android.kotlinVersion=1.9.22
android.composeCompilerVersion=1.5.10

# Dépôts Maven supplémentaires (vide par défaut)
android.extraMavenRepos=[]