# Paramètres JVM
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Crunch PNG en release
android.enablePngCrunchInReleaseBuilds=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=false
hermesEnabled=true

# Support images
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
expo.useLegacyPackaging=false

# Versions Kotlin / Compose Compiler
android.kotlinVersion=1.8.22
android.composeCompilerVersion=1.4.8

# Dépôts Maven supplémentaires (vide par défaut)
android.extraMavenRepos=[]