
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true
android.enablePngCrunchInReleaseBuilds=true

reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=false

# Moteur JS
hermesEnabled=true

# Support images
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false


EX_DEV_CLIENT_NETWORK_INSPECTOR=true
expo.useLegacyPackaging=false
android.kotlinVersion=1.7.20
android.composeCompilerVersion=1.3.2
android.extraMavenRepos=[]